### ISSUE TITLE
human v1 gtf causes error with velocyto.py: "ValueError: __len__() should return >= 0"

### ISSUE THREAD

**Issue by koetjen** [PoolLab/generecovery#4]
Exon annotations cause conflict in velocyto, presumably related to issue #73 there: https://github.com/velocyto-team/velocyto.py/issues/73 

```
%  velocyto run10x sample1 human_GRCh38_optimized_v1.gtf

2022-07-25 12:25:53,401 - DEBUG - Fixing corner cases of transcript models containg intron longer than 1000Kbp
Traceback (most recent call last):
  File "/opt/homebrew/Caskroom/miniforge/base/envs/velocity/bin/velocyto", line 8, in <module>
    sys.exit(cli())
  File "/opt/homebrew/Caskroom/miniforge/base/envs/velocity/lib/python3.9/site-packages/click/core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "/opt/homebrew/Caskroom/miniforge/base/envs/velocity/lib/python3.9/site-packages/click/core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "/opt/homebrew/Caskroom/miniforge/base/envs/velocity/lib/python3.9/site-packages/click/core.py", line 1657, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/opt/homebrew/Caskroom/miniforge/base/envs/velocity/lib/python3.9/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/opt/homebrew/Caskroom/miniforge/base/envs/velocity/lib/python3.9/site-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "/opt/homebrew/Caskroom/miniforge/base/envs/velocity/lib/python3.9/site-packages/velocyto/commands/run10x.py", line 112, in run10x
    return _run(bamfile=(bamfile, ), gtffile=gtffile, bcfile=bcfile, outputfolder=outputfolder,
  File "/opt/homebrew/Caskroom/miniforge/base/envs/velocity/lib/python3.9/site-packages/velocyto/commands/_run.py", line 186, in _run
    annotations_by_chrm_strand = exincounter.read_transcriptmodels(gtffile)
  File "/opt/homebrew/Caskroom/miniforge/base/envs/velocity/lib/python3.9/site-packages/velocyto/counter.py", line 544, in read_transcriptmodels
    tm.chop_if_long_intron()  # Change it in place
  File "/opt/homebrew/Caskroom/miniforge/base/envs/velocity/lib/python3.9/site-packages/velocyto/transcript_model.py", line 93, in chop_if_long_intron
    long_feats = [i for i in self.list_features if len(i) > maxlen and i.kind == ord("i")]
  File "/opt/homebrew/Caskroom/miniforge/base/envs/velocity/lib/python3.9/site-packages/velocyto/transcript_model.py", line 93, in <listcomp>
    long_feats = [i for i in self.list_features if len(i) > maxlen and i.kind == ord("i")]
ValueError: __len__() should return >= 0
```

**Comment by PoolLab** [comment]
Thanks for bringing this to my attention! The base optimized references will likely be problematic for velocyto due to the hybrid pre-mRNA approach (I have added gene length exons for genes which does a better job at capturing all intronic reads than just cellranger --include-introns attribute). However, I can upload velocyto compatible optimized genome annotations that should not yield these issues. I'll aim to get them up by tomorrow in the "updates" section.

**Comment by PoolLab** [comment]
The velocyto compatible genome annotations are now uploaded in the "Updates" section at thepoollab.org/resources page. We do not work with velocyto so haven't tested compatibility but do let us know if they do not work and we'll try to address the issue.

**Comment by sfortma2** [comment]
Hi, thank you for putting together this important resource. I tried running Velocyto with the new gtf file (human_GRCh38_optimized_v1_1_velocyto_exonic.gtf) but it is returning the same error as reported previously:

>Traceback (most recent call last):
  File "/data/user/sfortma2/.conda/envs/scanpy/bin/velocyto", line 8, in <module>
    sys.exit(cli())
  File "/data/user/sfortma2/.conda/envs/scanpy/lib/python3.7/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/data/user/sfortma2/.conda/envs/scanpy/lib/python3.7/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/data/user/sfortma2/.conda/envs/scanpy/lib/python3.7/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/data/user/sfortma2/.conda/envs/scanpy/lib/python3.7/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/data/user/sfortma2/.conda/envs/scanpy/lib/python3.7/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/data/user/sfortma2/.conda/envs/scanpy/lib/python3.7/site-packages/velocyto/commands/run10x.py", line 115, in run10x
    samtools_memory=samtools_memory, dump=dump, loom_numeric_dtype=dtype, verbose=verbose, additional_ca=additional_ca)
  File "/data/user/sfortma2/.conda/envs/scanpy/lib/python3.7/site-packages/velocyto/commands/_run.py", line 186, in _run
    annotations_by_chrm_strand = exincounter.read_transcriptmodels(gtffile)
  File "/data/user/sfortma2/.conda/envs/scanpy/lib/python3.7/site-packages/velocyto/counter.py", line 544, in read_transcriptmodels
    tm.chop_if_long_intron()  # Change it in place
  File "/data/user/sfortma2/.conda/envs/scanpy/lib/python3.7/site-packages/velocyto/transcript_model.py", line 93, in chop_if_long_intron
    long_feats = [i for i in self.list_features if len(i) > maxlen and i.kind == ord("i")]
  File "/data/user/sfortma2/.conda/envs/scanpy/lib/python3.7/site-packages/velocyto/transcript_model.py", line 93, in <listcomp>
    long_feats = [i for i in self.list_features if len(i) > maxlen and i.kind == ord("i")]
ValueError: __len__() should return >= 0

**Comment by schroeme** [comment]
Hi, I tried running Velocyto on data aligned to the latest version of your optimized mouse transcriptome ([Mouse mm10 scRNA-seq optimized transcripomic reference v.2.0](https://cloud.biohpc.swmed.edu/index.php/s/EweNmgEjG9HkjoD), and got the same error. Can you please advise on any work-arounds?

Traceback (most recent call last):
  File "/home/mschro/anaconda3/envs/velocyto/bin/velocyto", line 8, in <module>
    sys.exit(cli())
  File "/home/mschro/anaconda3/envs/velocyto/lib/python3.9/site-packages/click/core.py", line 1128, in __call__
    return self.main(*args, **kwargs)
  File "/home/mschro/anaconda3/envs/velocyto/lib/python3.9/site-packages/click/core.py", line 1053, in main
    rv = self.invoke(ctx)
  File "/home/mschro/anaconda3/envs/velocyto/lib/python3.9/site-packages/click/core.py", line 1659, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/mschro/anaconda3/envs/velocyto/lib/python3.9/site-packages/click/core.py", line 1395, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/mschro/anaconda3/envs/velocyto/lib/python3.9/site-packages/click/core.py", line 754, in invoke
    return __callback(*args, **kwargs)
  File "/home/mschro/anaconda3/envs/velocyto/lib/python3.9/site-packages/velocyto/commands/run.py", line 113, in run
    return _run(bamfile=bamfile, gtffile=gtffile, bcfile=bcfile, outputfolder=outputfolder,
  File "/home/mschro/anaconda3/envs/velocyto/lib/python3.9/site-packages/velocyto/commands/_run.py", line 186, in _run
    annotations_by_chrm_strand = exincounter.read_transcriptmodels(gtffile)
  File "/home/mschro/anaconda3/envs/velocyto/lib/python3.9/site-packages/velocyto/counter.py", line 544, in read_transcriptmodels
    tm.chop_if_long_intron()  # Change it in place
  File "/home/mschro/anaconda3/envs/velocyto/lib/python3.9/site-packages/velocyto/transcript_model.py", line 93, in chop_if_long_intron
    long_feats = [i for i in self.list_features if len(i) > maxlen and i.kind == ord("i")]
  File "/home/mschro/anaconda3/envs/velocyto/lib/python3.9/site-packages/velocyto/transcript_model.py", line 93, in <listcomp>
    long_feats = [i for i in self.list_features if len(i) > maxlen and i.kind == ord("i")]
ValueError: __len__() should return >= 0

**Comment by schroeme** [comment]
Hi, I am still having this error even when running velocyto masking out exons with length < 0 or > 1 megabase using the reference genome mentioned above. Can you please advise on any work-arounds or other issues with the GTF that might be triggering this error?

From the [velocyto documentation](https://velocyto.org/velocyto.py/tutorial/cli.html), 

"velocyto assumes that the gtf file follows the [GENCODE gtf format description](https://www.gencodegenes.org/gencodeformat.html). However some mandatory field are relaxed to extend compatibility to a wider set of gtf files. In particular the gtf file will have to:

Contain the 3rd column entry feature-type. Note that only the exon entry of the gtf file marked as exon`in this column will be considered and therefore the requirements below only apply to the ``exon` labeled lines.
Contain, in the 9th column, the key-value pair transcript_id, containing an unique identified for the transcript model.
Contain, in the 9th column, the key-value pair transcript_name (Optional, if not present it will be set to the value of transcript_id)
Contain, in the 9th column, the key-value pair gene_id, containing an unique identified for the gene.
Contain, in the 9th column, the key-value pair gene_name (Optional, if not present it will be set to the value of gene_id)
Contain, in the 9th column, the key-value pair exon_number (Recommended but optional, if not provided velocyto will sort exons in memory and number them)"

It seems like the optimized gtf meets all these requirements, except maybe has some violations of exon length.

**Comment by ollieeknight** [comment]
i'm having this issue too, were there ever any full fixes @PoolLab @koetjen?
